services:
  object_detection:
    build:
      context: ..                # build context is parent folder
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKSPACE: ${WORKSPACE:-/workspace}
    runtime: nvidia
    container_name: object_detection
    network_mode: host
    privileged: true
    ipc: host
    user: root
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      YOLO_MODEL: yolov8s # choose model 
      RUN_MODE: standalone # or: composite
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      PULSE_SERVER: ${PULSE_SERVER}
      LIBGL_ALWAYS_SOFTWARE: "1"
      RMW_IMPLEMENTATION: "rmw_cyclonedds_cpp"
    volumes:
      - /dev/input:/dev/input # This is only required to recognise the joystick if it is turned on after the container started
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../..:/workspaces:cached

    command: ["bash", "/workspaces/object_detection/entrypoint.sh"]
